App.tsx, src/commons/components/CustomNavigator/CustomNavigator.tsx, src/commons/components/Postcard/Postcard.tsx, src/commons/components/Postcard/Postcard.types.ts, src/commons/components/TapComponent/TapScreens.tsx, src/screens/Matching/Matching.styles.ts, src/screens/Matching/Matching.tsx
1. 전역 스타일 적용
* customNavigator에 전역 margin 적용하였습니다.
* TabNavigation 스타일 일부 수정
2. 매칭 탭 구조 개발
* 버튼 클릭 시 컴포넌트(받은 엽서, 발신한 엽서)
=> 전역 스타일링으로 인해 일부 화면 꺠질 수 있는데 SafetyAreaView를 각 컴포넌트에서 지워주시면 됩니다.
=> [개발] 전역 스타일 적용 & 매칭 탭 구조 

src/screens/Matching/Postcard/Send/SendPostcard.styles.ts, src/screens/Matching/Postcard/Send/SendPostcard.tsx
* 상태에 따른 이미지 블러 처리 기능 추가
* 상태 버튼 폰트사이즈 변경
=> feat: 상태에 따른 이미지 블러 처리 추가

src/commons/components/CustomNavigator/CustomNavigator.tsx, src/commons/store/useAgreement.ts, src/screens/TermsOfService/TermsOfService.tsx
- 마케팅 체크 박스 누르면 adAgreementPolicy에 값 저장
=> feat: update useAgreetment boolean

src/screens/TermsOfService/TermsOfService.styles.ts, src/screens/TermsOfService/TermsOfService.tsx
=> chore: 약관동의 페이지 수정

package.json, src/screens/Matching/Postcard/Receive/ReceivePostcardDetail.styles.ts, src/screens/Matching/Postcard/Receive/ReceivePostcardDetail.tsx, src/screens/MyLibrary/MyBookInfoModify/MyBookInfoModify.styles.ts, src/screens/MyLibrary/MyBookInfoModify/MyBookInfoModify.tsx, src/screens/MyLibrary/MyBookInfoModify/MyBookInfoModify.types.ts, src/screens/MyLibrary/MyLibrary.styles.ts, src/screens/MyLibrary/MyLibrary.tsx
=> [개발] 내 서재 책 정보 및 수정 모달 구현

src/commons/components/CustomHeader/CustomHeader.tsx, src/commons/components/CustomHeader/CustomHeader.types.ts, src/commons/components/CustomModal/ModalButtons/ModalButtons.styles.ts, src/commons/hooks/useHeaderControl.tsx, src/commons/store/usePostcardCounter.ts, src/screens/Home/screens/Home/units/Profile/Profile.tsx, src/screens/Library/Library.styles.ts, src/screens/Library/Library.tsx, src/screens/Matching/Postcard/Receive/ReceivePostcard.styles.ts, src/screens/Matching/Postcard/Receive/ReceivePostcard.tsx, src/screens/Matching/Postcard/Receive/ReceivePostcardDetail.tsx, src/screens/Matching/Postcard/Send/SendPostcard.styles.ts
1. 받은엽서 > 엽서 상세 > 상대방 엽서보러가기 연결
2. 엽서 부족 모달 > 충전 시간 확인하러가기 연결
=> [개발] 화면간 이동 연결

src/commons/api/memberStyle.api.ts, src/commons/components/CustomNavigator/CustomNavigator.tsx, src/commons/components/MbtiItem/MbtiItem.styles.ts, src/commons/components/MbtiItem/MbtiItem.tsx, src/commons/components/ModifyMBTI/ModifyMBTI.styles.ts, src/commons/components/ModifyMBTI/ModifyMbtiItem.tsx, src/commons/store/useStyle.ts, src/screens/InitStyle/ModifyStyle.tsx, src/screens/InitStyle/units/CommStyle.tsx, src/screens/InitStyle/units/DateCost.tsx, src/screens/InitStyle/units/Mbti.tsx, src/screens/InitStyle/units/OppositeSex.tsx, src/screens/InitStyle/units/PersonalQuestion.tsx, src/screens/InitStyle/units/SmokeDrink.tsx
-Post style, Get style 함수 생성
-useStyle 변수명 수정
-mbti 텍스트 스타일 수정
-useStyle에 resetStyleInfo 함수 추가
=> feat: Post style 추가

src/screens/TermsOfService/TermsOfService.styles.ts, src/screens/TermsOfService/TermsOfService.tsx
- 체크박스 사이즈 크게
- 줄 간격 벌림
- 비활성화 버튼 하나로 합체
=> style:약관 동의 페이지 스타일 수정

src/screens/InitUserInfo/InitUserInfo.styles.ts, src/screens/TermsOfService/TermsOfService.styles.ts, src/screens/TermsOfService/TermsOfService.tsx
=> style: 약관동의 스타일 수정

src/commons/components/MbtiItem/MbtiItem.styles.ts, src/commons/components/MbtiItem/MbtiItem.tsx, src/screens/InitStyle/InitStyle.styles.ts, src/screens/InitStyle/units/CommStyle.tsx, src/screens/InitStyle/units/DateCost.tsx, src/screens/InitStyle/units/Mbti.tsx, src/screens/InitStyle/units/OppositeSex.tsx, src/screens/InitStyle/units/PersonalQuestion.tsx, src/screens/InitStyle/units/SmokeDrink.tsx, src/screens/InitUserInfo/InitUserInfo.styles.ts, src/screens/InitUserInfo/units/CompletePage.tsx, src/screens/InitUserInfo/units/EmailAuth.tsx, src/screens/InitUserInfo/units/GenderBirth.tsx, src/screens/InitUserInfo/units/InfoOpenChat.tsx, src/screens/InitUserInfo/units/ModalContent.tsx, src/screens/InitUserInfo/units/OpenChatLink.tsx, src/screens/InitUserInfo/units/ProfileImage.tsx, src/screens/InitUserInfo/units/SchoolStudentID.tsx, src/screens/InitUserInfo/units/WaitConfirm.tsx, src/screens/Login/KakaoLogin.tsx, src/screens/TermsOfService/TermsOfService.styles.ts, src/screens/TermsOfService/TermsOfService.tsx
1. mbti 선택된 건 눌러도 변화x
2. 스타일 페이지 마진 제거
3. 약관 동의 페이지 버튼에 패딩 추가
4. 유저 정보 페이지 마진 제거, 스타일 수정
5. DatePicker에 생년월일 초기값 수정
6. 카카오 로그인 토스트 메세지 수정
=> fix: 1차 단위 테스트 수정 (유저 정보, 스타일, 약관 동의)

src/commons/api/library.api.ts, src/commons/api/matching.api.ts, src/commons/utils/http.api.ts, src/screens/Home/screens/Home/units/Profile/Profile.tsx, src/screens/Home/screens/Matching/hooks/useFetchReceivePostcard.ts, src/screens/Home/screens/Matching/hooks/useFetchSendPostcard.ts, src/screens/Library/Library.tsx, src/screens/Library/Library.types.ts, src/screens/Library/SendPostcardModal/SendPostcardModal.tsx, src/screens/Library/SendPostcardModal/SendPostcardModal.types.ts, src/screens/Matching/Matching.tsx, src/screens/Matching/Matching.types.ts, src/screens/Matching/Postcard/Receive/ReceivePostcard.tsx, src/screens/Matching/Postcard/Receive/ReceivePostcard.types.ts, src/screens/Matching/Postcard/Receive/ReceivePostcardDetail.tsx, src/screens/Matching/Postcard/Send/SendPostcard.tsx, src/screens/Matching/Postcard/Send/SendPostcard.types.ts
내서재, 상대방 서재, 매칭 API 연동
//todo
엽서 클릭 시 엽서 진짜 사용할거냐는 모달 추가하기..
프로필 이미지 API 수정하기..
프로필 이미지 수정중 상태 바 추가하기..
=> 내서재, 매칭 API

src/commons/api/memberPushAlarm.api.ts, src/commons/components/FavBookList/FavBookList.tsx, src/commons/components/TapComponent/TapScreens.tsx, src/commons/contents/agreement/agreementUrls.ts, src/commons/hooks/useTruncateText.ts, src/screens/Home/HomeStack.tsx, src/screens/Home/screens/Home/Home.tsx, src/screens/InitBook/InitBookStack.styles.ts, src/screens/InitBook/initBookStack.schema.ts, src/screens/InitBook/screens/AddBook/AddBook.tsx, src/screens/InitBook/screens/InitQuiz/InitQuiz.tsx, src/screens/InitBook/screens/SearchBook/SearchBook.tsx, src/screens/Login/screens/LoginHome/LoginHome.tsx, src/screens/Notice/Notice.tsx, src/screens/Notice/hooks/useDeleteAlarm.ts, src/screens/Notice/hooks/useGetAlarms.ts, src/screens/Setting/SettingStack.styles.ts, src/screens/Setting/SettingStack.tsx, src/screens/Setting/screens/Account/units/MatchingContent/MatchingContent.tsx, src/screens/Setting/screens/Setting/Setting.tsx, src/screens/TermsOfService/TermsOfService.tsx
refactor: 페이지 이동처리 로직 수정
feat: 알림 페이지 - 알림 API (전체삭제, 선택삭제, 전체조회) 연결
feat: useTruncateText훅 구현
refactor: TapScreens Home 탭 - unmountOnBlur 속성 연결
refactor: 약관 페이지 - 알림 허용 훅 연결
refactor: 매칭 비화설화 모달 - TextBox 컴포넌트 placeholder 속성 추가
refactor: 책 추가 페이지 - 1차 수정 방안 반영
feat: 알림 허용 훅 사용
refactor: 불필요한 참조 제거
refactor: 세팅스택 페이지 스타일링 수정
=> 1차 수정 방안 반영 및 useTruncateText훅 구현과 알림 페이지 API 연결

src/commons/api/memberPushAlarm.api.ts, src/commons/components/FavBookList/FavBookList.tsx, src/commons/hooks/useGetAlarms.ts, src/commons/hooks/useTruncateText.ts, src/commons/utils/truncateText.ts, src/screens/Home/screens/Home/units/Profile/Profile.tsx, src/screens/InitBook/InitBookStack.styles.ts, src/screens/InitBook/screens/InitQuiz/InitQuiz.tsx, src/screens/Notice/Notice.tsx, src/screens/Notice/hooks/useDeleteAlarm.ts, src/screens/Setting/SettingStack.styles.ts, src/screens/Setting/SettingStack.tsx, src/screens/Setting/screens/Setting/Setting.tsx
rename: useGetAlarm훅 공용폴더로 이동
refactor: useTruncateText훅 유틸리티 함수로 변경
refactor: 알림 전체삭제 함수 로직 수정
refactor: useManageMargin 훅 스크린 => 스택에서 사용으로 변경 및 스타일링 수정
refactor: 퀴즈페이지 스타일링 수정
=> useTruncateText훅 유틸리티 함수로 변경 및 알림 전체삭제 함수 로직 수정 및 퀴즈페이지, 세팅페이지 스타일링 수정

src/commons/api/matching.api.ts, src/commons/components/CustomNavigator/CustomNavigator.tsx, src/commons/components/ModifyMBTI/ModifyMbtiItem.tsx, src/commons/components/TapComponent/TapScreens.tsx, src/commons/hooks/useInitialRouteName.ts, src/commons/hooks/useMovePage.ts, src/commons/utils/http.api.ts, src/screens/Home/HomeStack.tsx, src/screens/Home/screens/Home/units/Profile/Profile.tsx, src/screens/Home/screens/Matching/hooks/useFetchReceivePostcard.ts, src/screens/Home/screens/Matching/hooks/useFetchSendPostcard.ts, src/screens/InitStyle/ModifyStyle.tsx, src/screens/Library/Library.tsx, src/screens/Library/Library.types.ts, src/screens/Library/LibraryStack.tsx, src/screens/Library/MyBookInfoModify/MyBookInfoModify.tsx, src/screens/Library/ViewStyle/ViewStyle.tsx, src/screens/Matching/Matching.styles.ts, src/screens/Matching/Matching.tsx, src/screens/Matching/MatchingStack.tsx, src/screens/Matching/Postcard/Receive/ReceivePostcard.styles.ts, src/screens/Matching/Postcard/Receive/ReceivePostcard.tsx, src/screens/Matching/Postcard/Receive/ReceivePostcard.types.ts, src/screens/Matching/Postcard/Receive/ReceivePostcardDetail.styles.ts, src/screens/Matching/Postcard/Receive/ReceivePostcardDetail.tsx, src/screens/Matching/Postcard/Send/SendPostcard.styles.ts, src/screens/Matching/Postcard/Send/SendPostcard.tsx, src/screens/Matching/Postcard/Send/SendPostcard.types.ts
- 엽서 읽기 전 방지 모달 추가
-  내서재 > 프로필 수정 여부 감지 기능 추가
- 엽서 차감 API 연동
=> 매칭, 내서재, 상대방 서재 API 연동

src/screens/InitUserInfo/units/components/RejectedInfo/StudentID.tsx, src/screens/Library/Library.tsx
=> chore: s3 업로드 uuid로 변경

src/screens/InitBook/screens/InitQuiz/InitQuiz.tsx, src/screens/InitStyle/ModifyStyle.tsx, src/screens/InitStyle/units/PersonalQuestion.tsx, src/screens/InitUserInfo/ModifyUserinfo.tsx, src/screens/InitUserInfo/units/OpenChatLink.tsx, src/screens/InitUserInfo/units/components/RejectedInfo/OpenChat.tsx, src/screens/Library/MyBookInfoModify/MyBookInfoModify.tsx
- 텍스트 필드에 placeholder 추가
- 개인 질문 수정에서 마지막 한 글자 삭제 안되는 것 수정
=> style: placeholder(부적절, 유해한 콘텐츠...)추가

.gitignore, build.sh, src/screens/Home/screens/Product/Product.tsx, src/screens/InitBook/screens/AddBook/AddBook.tsx, src/screens/InitStyle/initStyle.tsx, src/screens/InitStyle/units/DateCost.tsx, src/screens/Library/Library.tsx, src/screens/Matching/Matching.tsx, src/screens/Matching/Postcard/Receive/ReceivePostcard.tsx
1. "책갈피" => "엽서"로 텍스트 변경
2. 키입력 페이지 - 스타일 스택에서 제외
3. 빌드 스크립트 - 깃이그노어 삭제 로직 추가
4. 깃이그노어 설정 추가
=> v0.1.3 업데이트를 위한 수정

src/screens/Home/screens/Product/Product.tsx, src/screens/InitBook/screens/AddBook/AddBook.tsx, src/screens/InitStyle/initStyle.tsx, src/screens/InitStyle/units/DateCost.tsx, src/screens/Library/Library.tsx, src/screens/Matching/Matching.tsx, src/screens/Matching/Postcard/Receive/ReceivePostcard.tsx, src/screens/Setting/screens/Setting/units/ModalContent/AlarmContent.tsx
<li>update: 재화명 엽서에서 책갈피로 변경
<li>update: 키 입력 페이지 - 스타일 스택에서 추가
<li>feat: 알림 온오프 모달 컴포넌트 구현
=> 재화명 "엽서"에서 "책갈피"로 변경 및 키 입력 페이지 추가 및 알림 온오프 모달 컴포넌트 구현

src/commons/websocket/websocketClient.ts, src/screens/Chat/ChatDetail.tsx
전송 실패한 메세지 다시 보내면, 실패한거 사라지고 다시 보내져야함. 
메세지 보내고 나면 전송버튼 계속 불 들어와있음. 수정 필요
키보드가 채팅입력칸 가리는거 수정 안됨
=> feat : fix all error

package-lock.json, package.json
=> Revert "chore: 리액트 쿼리 의존성 추가"
